In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm import tqdm
import numpy as np

### Book Details Scraping

In [10]:
link='https://books.toscrape.com/catalogue/page-1.html'

In [11]:
res=requests.get(link)
soup2=BeautifulSoup(res.text, 'html.parser')

In [12]:
data=[]
for i in tqdm(range(1,51)):
    link='https://books.toscrape.com/catalogue/page-'+str(i)+'.html'
    res=requests.get(link)
    soup2=BeautifulSoup(res.text, 'html.parser')
    
    for sp in soup2.find_all('li', class_='col-xs-6 col-sm-4 col-md-3 col-lg-3'):
        book_link='https://books.toscrape.com/catalogue/'+sp.find_all('a')[-1].get('href')
        title=sp.find_all('a')[-1].get('title')
        image_link='https://books.toscrape.com/catalogue/'+sp.find('img').get('src')
        rating=sp.find('p').get('class')[-1]
        price=sp.find('p',class_='price_color').text[1:]
        instock=sp.find('p', class_='instock availability').text.strip()
    
        data.append([title, rating, price, instock,book_link,image_link ])

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [01:24<00:00,  1.69s/it]

In [13]:
pd.DataFrame(data, columns=['title', 'rating', 'price', 'instock', 'book_link', 'image_link'])

,title,rating,price,instock,book_link,image_link
0,A Light in the Attic,Three,£51.77,In stock,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/catalogue/../media/...
1,Tipping the Velvet,One,£53.74,In stock,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/catalogue/../media/...
2,Soumission,One,£50.10,In stock,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/catalogue/../media/...
3,Sharp Objects,Four,£47.82,In stock,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/catalogue/../media/...
4,Sapiens: A Brief History of Humankind,Five,£54.23,In stock,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/catalogue/../media/...
...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,One,£55.53,In stock,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/catalogue/../media/...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Four,£57.06,In stock,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/catalogue/../media/...
997,A Spy's Devotion (The Regency Spies of London #1),Five,£16.97,In stock,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/catalogue/../media/...
998,1st to Die (Women's Murder Club #1),One,£53.98,In stock,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/catalogue/../media/...
999,"1,000 Places to See Before You Die",Five,£26.08,In stock,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/catalogue/../media/...

In [14]:
df.head()

,quote,name,author_link,tags,main_author_link
0,“The world as we have created it is a process ...,Albert Einstein,/author/Albert-Einstein,change,https://quotes.toscrape.com/author/Albert-Eins...
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,/author/J-K-Rowling,abilities,https://quotes.toscrape.com/author/J-K-Rowling
2,“There are only two ways to live your life. On...,Albert Einstein,/author/Albert-Einstein,inspirational,https://quotes.toscrape.com/author/Albert-Eins...
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,/author/Jane-Austen,aliteracy,https://quotes.toscrape.com/author/Jane-Austen
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,/author/Marilyn-Monroe,be-yourself,https://quotes.toscrape.com/author/Marilyn-Monroe